name: .NET 8 API Continuous Deployment on Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Build with dotnet
      run: dotnet build backend --configuration Release

    - name: Publish with dotnet
      run: dotnet publish backend -c Release -o ${{github.workspace}}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'floorspaces'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{github.workspace}}/publish